### ISSUE TITLE
TypeScript 2.7 breaks `@types/lodash`

### ISSUE THREAD

**Issue by RangarajKaushikSundar** [TypeStrong/typedoc#696]
Using Typescript Version 2.7.1 seems to break @types/lodash.
```
node_modules/@types/lodash/index.d.ts:12651:53 - error TS2344: Type 'T' does not satisfy the constraint 'object'.

12651         isWeakSet<T>(value?: any): value is WeakSet<T>;
```

The solution mentioned online is to switch back to typescript 2.6.2. Please advise.

**Comment by aciccarello** [comment]
What version of `@types/lodash` does this affect?

**Comment by leafriend** [comment]
It seems to be problem of `@types/lodash` or TypeScript 2.7.1.

Works with @types/lodash@4.14.95:
```
mkdir types-lodash
cd types-lodash
npm init -y
npm i -D typescript@2.7.1 @types/lodash@4.14.95
cp /dev/null index.ts
npx tsc --init
npx tsc
```

Broken with @types/lodash@4.14.96:
```
mkdir types-lodash
cd types-lodash
npm init -y
npm i -D typescript@2.7.1 @types/lodash@4.14.96
cp /dev/null index.ts
npx tsc --init
npx tsc
```

**Comment by leafriend** [comment]
New TypeScript version 2.7.2 is OK now:

```
mkdir types-lodash
cd types-lodash
npm init -y
npm i -D typescript@2.7.2 @types/lodash@4.14.96
# or use latest `@types/loadash` version 4.14.104
# npm i -D typescript@2.7.2 @types/lodash^4.14.104
cp /dev/null index.ts
npx tsc --init
npx tsc
```
