### ISSUE TITLE
TypeDoc not respecting `exclude` in `typedoc.json` or in `tsconfig.json` monorepo

### ISSUE THREAD

**Issue by bracesproul** [TypeStrong/typedoc#2473]
## Search terms

TypeDoc not respecting `exclude` in `typedoc.json` or in `tsconfig.json` inside monorepo project.

## Expected Behavior

TypeDoc to respect the exclude field listing `dist` folder.

## Actual Behavior

TypeDoc fails to respect the `exclude` field inside `typedoc.json` for `dist` folders. I've tried the following patters:
`dist`
`**/dist`
`**/dist/**`
`dist/**`
It also fails to respect the `exclude` field inside the root `tsconfig.json`:

```json
"exclude": [
    ...
    "**/dist/",
    "langchain-core/dist/",
  ]
```

Error:

```bash
../../langchain-core/src/utils/env.ts:3:9 - error TS2451: Cannot redeclare block-scoped variable 'Deno'.

3   const Deno:
          ~~~~

  ../../langchain-core/dist/utils/env.d.ts:2:11
    2     const Deno: {
                ~~~~
    'Deno' was also declared here.
```

## Steps to reproduce the bug

1. Clone [langchain.js](https://github.com/langchain-ai/langchainjs)
2. Run `yarn install`
3. Remove `skipErrorChecking` from `docs/api_refs/typedoc.json`
4. Run `yarn build` from inside `docs/api_refs/`

## Environment

-   Typedoc version: `latest` (using `npx typedoc`) - side note, is this a bad practice? Not really sure.
-   TypeScript version: `~5.1.6`
-   Node.js version: `v20.10.0`
-   OS: `macOS`

**Comment by Gerrit0** [comment]
That build system is... completely incomprehensible to me...

That error is coming directly from TypeScript, TypeDoc is accurately showing the errors you'd get if you ran tsc with that tsconfig.

```bash
npx tsc --project ../../tsconfig.json --noEmit
```

**Comment by Gerrit0** [comment]
> side note, is this a bad practice? Not really sure.

Personally, I'd recommend locking as a dev dependency, there are usually breaking changes between 0.x versions, so you run the risk of broken builds. It's nice to be able to check out an _old_ commit and still have a working build.
