### ISSUE TITLE
--exclude option does not work

### ISSUE THREAD

**Issue by Lodin** [TypeStrong/typedoc#395]
Trying to generate documentation for my project I have faced with the problem that typedoc tried to generate documentation for `spec.ts` files I excluded in the typedoc command in my `package.json` script section:
```json
{
    "docs": "typedoc --out docs --exclude **/*.spec.ts src",
}
```
It worked even when I moved my tests from `src` to the separate `test` directory. So I assume that specifying a directory as an argument of `typedoc` command does not work too. 

I googled a lot, but found nothing except an old [issue](https://github.com/TypeStrong/typedoc/issues/170) that did not help me at all despite I tried all of examples from there. 

So I decided to look at the code, and after some investigation found that it might be a problem at this [line](https://github.com/TypeStrong/typedoc/blob/master/src/lib/application.ts#L275). When I added an `exclude` check from [here](https://github.com/TypeStrong/typedoc/blob/master/src/lib/application.ts#L262), it compiled as it should, only for non-spec files.

I use the `typedoc@0.5.5`, `typescript@2.2.0-dev`.

**Comment by ollwenjones** [comment]
Same problem here.

**Comment by mjkkirschner** [comment]
same here.

**Comment by janerikmai** [comment]
+1

**Comment by goodmind** [comment]
How to do multiple excludes? It seems that this not working:
```
typedoc --out docs --exclude '**/+(test|node_modules)/**/*.ts' packages/filte
ring --module commonjs
```

**Comment by tonysneed** [comment]
I have this:

```json
"docs": "typedoc --out dist/docs --target es6 --theme minimal --mode modules --exclude **/*.spec.ts src",
```

But my spec files are still included in the docs/modules folder .  Any ideas?

**Comment by blakeembrey** [comment]
@tonysneed Are you on Windows? Have you tried quoting the argument like `--exclude "**/*.spec.ts"`?

**Comment by tonysneed** [comment]
@blakeembrey That worked! Thanks!!

**Comment by Tokimon** [comment]
I have the same issue (using **windows**). I have tried basically everything there is to try but it still includes my test files.
I have a simple call: `typedoc --out ./docs --exclude "./test/**/*.*"`. But it totally ignores my exclude settings and keeps including my test files. I have tried: `typedoc.json`, `typedoc.js`, `typedocOptions` and the CLI argument but nothing works. I have even tried to specify the path to my tsconfig (`./tsconfig.json` that even have the same exclude: `./test/**/*.*`) but to no avail. I have no clue what I am doing wrong.

As a side note (and probably another issue); if I have a `typedoc.js` and run the typedoc command it simply opens my typedoc.js file and stops running (again this is on **windows**).

**Comment by Gerrit0** [comment]
If anyone can provide a repo that can reproduce this issue it would help greatly. As far as I can tell the exclude option works correctly so long as the minimatch glob is set correctly. 

A few things to remember:

1. Always start with `**/`, the pattern will not match anything if you fail to do this since Typedoc passes the full path of files to Minimatch.
1. Remember to quote your globs - your shell may be expanding them.

If you aren't sure what will be excluded, I've set up a simple [RequireBin demo](http://requirebin.com/?gist=4087a581b706bfec194a96b7e42cb978) to demonstrate which patterns do what.

Examples:

1. Ignore node_modules, tests folder, `**/{test,node_modules}/**/*.ts`
1. Ignore node_modules, .spec.ts files, `**/{node_modules/**/*,*.spec}.ts`
1. Ignore test files `**/.{spec,test}.ts`

**Comment by Tokimon** [comment]
Isn't having to add the `**/` in the beginning of your expression a bit atypical? Usually the expression is joined with `cwd` when using other APIs (Like TypeScript). But maybe there is some reason for doing it like this I have missed. However this confusion seems to be the root of the confusion I think.

Personally I finally dug into your code a found out that I had to add the `**/` to the beginning of my expression for it to work. But then it also works great. But it was confusing. May an idea to add it as a comment in the docs?

**Comment by dupski** [comment]
For people having problems with multiple excludes, I got it working with `0.11` using the --config option and a JS config file.

See https://github.com/TypeStrong/typedoc/issues/170#issuecomment-388607358

**Comment by balupton** [comment]
Seems there are two issues here:

1. User error of blobs being interpreted by the shell, instead of by typedoc, which is caused by not wrapping the exclude value in a string.

2. The request to support multiple `--exclude` arguments.

For 2, I've created https://github.com/TypeStrong/typedoc/issues/905 to continue it.

For 1, seems like it (and thus this issue) can be closed.

**Comment by Gerrit0** [comment]
Closing this as the original issue is handled by #896 and later issues have been resolved or split into other issues.

**Comment by lianulloa** [comment]
I am experiencing this issue now

I am trying to run typedoc like this:
`npx typedoc --entryPointStrategy Expand --exclude "**/*+(.spec|.test).ts"  src/lib`

I got the pattern from the [docs](https://typedoc.org/documents/Options.Input.html#exclude)

"typedoc": "^0.28.14"
"typescript": "^5.9.3",

```jsonc
// tsconfig.json
{
  //...
  "exclude": ["node_modules", "**/*.test.{tsx,ts}", "src/test",]
}
```
Running the command gives error output like
```bash
src/lib/styling.test.ts:5:1 - error TS2582: Cannot find name 'describe'. Do you need to install type definitions for a test runner? Try `npm i --save-dev @types/jest` or `npm i --save-dev @types/mocha`.

 describe("getHslColor", () => {
  ~~~~~~~~
```
