### ISSUE TITLE
Transitive module imports no longer supported

### ISSUE THREAD

**Issue by alalonde** [TypeStrong/typedoc#1293]
We have a large [codebase](https://github.com/convergencelabs/convergence-client-javascript) with a lot of `index.ts` files that themselves import other nested `index.ts` files within subdirectories.  As of 0.17 Typedoc fails to detect these properly.

## Search terms
Error: Expected a symbol for node with kind <>

## Expected Behavior
[Transitive imports](https://github.com/convergencelabs/typedoc-plugin-custom-modules/tree/master/test/module-def-not-parent), such as:
```
// index.ts
export * from "./mod1";

// mod1/index.ts
export * from "./module";

// mod1/module.ts
export class ModuleClass{}
...
```
Should be detected and processed properly. 

## Actual Behavior
`Error: Expected a symbol for node with kind StringLiteral`

see my [latest build](https://travis-ci.org/github/convergencelabs/typedoc-plugin-custom-modules/builds/682200116#L370) after upgrading to 0.17

## Steps to reproduce the bug
```
git clone git@github.com:convergencelabs/typedoc-plugin-custom-modules.git
cd typedoc-plugin-custom-modules
npm install
npm run test
```

3 of the 4 test suites in this project have this pattern and currently fail.

## Environment
- Typedoc version: 0.17.6
- TypeScript version: 3.8.3
- Node.js version: 10.8
- OS: macOS

**Comment by acao** [comment]
slightly different, but a similar error `Error: Expected a symbol for node with kind Identifier`

caused by this kind of export:

```ts
export { language as monarchLanguage } from 'monaco-editor/esm/vs/basic-languages/graphql/graphql';
```

removing this line fixed it.

**Comment by Gerrit0** [comment]
Well that's.. unfortunate. I didn't even think to check this since TypeScript seems to work with that type of input just fine. I'll try to take a closer look this weekend.

**Comment by Gerrit0** [comment]
Looks like alalonde's issue at least is not a bug. ignoreCompilerErrors is a dangerous flag. Once I turned it off the reason immediately became obvious.

> Using TypeScript 3.8.3 from C:\Users\gtbir\Desktop\typedoc-plugin-custom-modules\node_modules\typescript\lib
Error: C:/Users/gtbir/Desktop/typedoc-plugin-custom-modules/test/module-def-in-same-file/module.ts(6)
 Cannot find module '../multiple-ancestor-modules'.
      1) module-def-in-same-file converts fixtures
      2) module-def-in-same-file matches specs
    module-def-not-parent

This is because as of 0.16.0, the TSConfig option reader isn't enabled by default. That your tests worked at all in 0.16 was just luck.

```diff
@ -1,4 +1,4 @@
-import { Application, normalizePath, resetReflectionID, ProjectReflection } from "typedoc";
+import { Application, normalizePath, resetReflectionID, ProjectReflection, TSConfigReader } from "typedoc";
import * as fs from "fs";
import * as Path from "path";
import Assert = require("assert");
@ -26,6 +26,7 @@ describe("Converter", () => {
  });

  let app = new Application();
+  app.options.addReader(new TSConfigReader());
  app.bootstrap(testConfig);

  fs.readdirSync(base).forEach(directory => {
```

---

@acao do you have ignoreCompilerErrors turned on as well?

**Comment by alalonde** [comment]
Ah, yes, good catch. I must've had that turned on as a workaround at some point and never disabled it.  Thank you.
