### ISSUE TITLE
Errors after 0.20.0 upgrade

### ISSUE THREAD

**Issue by WilliamsEC** [TypeStrong/typedoc#2710]
## upgrade 0.20.x

--excludeNotExported --ignoreCompilerErrors

I've been passed over some app which we need to maintain. They haven't had any maintenance for a few years and I'm in the middle of trying to update them to the latest packages. I've not used TypeDoc before and when we upgraded to 0.20.0 or higher we start hitting some errors which seem to be related to the switches --excludeNotExported --ignoreCompilerErrors which have now been depreciated. My question is what would be the alternative configuration to use now these have gone?

This is the configuration file we have been using since the upgrade:

typedoc.json
```
{
  "$schema": "https://typedoc.org/schema.json",
  "entryPoints": ["./src/index.tsx"],
  "out": "./docs",
  "excludeNotDocumented": true
}
```

I've also added the tsconfig.json as a command line to TypeDoc:

tsconfig.json

```
{
  "include": ["src", "types", "test"],
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "lib": ["dom", "esnext"],
    "importHelpers": true,
    "declaration": true,
    "sourceMap": true,
    "rootDir": "./src",
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": "./",
    "paths": {
      "@": ["./"],
      "*": ["src/*", "node_modules/*"]
    },
    "jsx": "react",
    "esModuleInterop": true
  }
}

```
Example of errors now appearing which aren't there pre 0.20.0:

node_modules/@aws-sdk/client-lex-runtime-service/dist-types/LexRuntimeServiceClient.d.ts:7:30 - error TS2305: Module '"@aws-sdk/smithy-client"' has no exported member 'DefaultsMode'.

7 import { Client as __Client, DefaultsMode, SmithyConfiguration as __SmithyConfiguration, SmithyResolvedConfiguration as __SmithyResolvedConfiguration } from "@aws-sdk/smithy-client";
                               ~~~~~~~~~~~~

node_modules/@aws-sdk/client-lex-runtime-service/dist-types/models/LexRuntimeServiceServiceException.d.ts:1:10 - error TS2305: Module '"@aws-sdk/smithy-client"' has no exported member 'ServiceException'.

1 import { ServiceException as __ServiceException, ServiceExceptionOptions as __ServiceExceptionOptions } from "@aws-sdk/smithy-client";
           ~~~~~~~~~~~~~~~~

Thanks

Ed

**Comment by Gerrit0** [comment]
> excludeNotExported

No longer necessary since 0.20, typedoc only documents exports.

> ignoreCompilerErrors

Using this is dangerous, the compiler doesn't follow its api contracts when there are compiler errors, so this can result in crashes.

Issues with undefined types in declaration files should be suppressed with TypeScript's `skipLibCheck` option if possible. If not possible, you could use TypeDoc's `skipErrorChecks` option with the caveat that any issues encountered when using that option are officially unsupported and will not be fixed.
