### ISSUE TITLE
Upgrade to TypeScript 3.x

### ISSUE THREAD

**Issue by athasach** [TypeStrong/typedoc#733]
When using new features of TypeScript 2.8 such as this one: https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#improved-control-over-mapped-type-modifiers

TypeDoc cannot process TypeScript files that use those features.

Update May 31, 2018: TypeScript 2.9 is out now.

Update July 30, 2018: TypeScript 3.0 is out now. https://blogs.msdn.microsoft.com/typescript/2018/07/30/announcing-typescript-3-0/

**Comment by sunderhus** [comment]
Already tested manually to add the newest version of typescript in the typedoc itself and it worked just fine


```
$ typedoc ./src --out ./doc --module commonjs --target ES5 --hideGenerator --mode file --readme none --theme minimal --excludePrivate

Using TypeScript 2.8.1 from /home/myuser/Documents/mylib/node_modules/typedoc/node_modules/typescript/lib
Rendering [========================================] 100%

Documentation generated at /home/myuser/Documents/mylib/doc

Done in 4.60s.

```

**Comment by alisahinozcelik** [comment]
I have tried to use [homomorphic mapped types](https://github.com/Microsoft/TypeScript/pull/12563) but got this error:

```typescript
interface IOptions {
  a?: string;
  b?: number;
}

type TNonOptionalOptions = {[P in keyof IOptions]-?: IOptions[P]};
```
`Error: file.ts(6)
 ';' expected.
Error: file.ts(6)
 Expression expected.
Error: file.ts(6)
 Expression expected.
Error: file.ts(6)
 Declaration or statement expected.
`

I have also tried `Required<T>` type from `lib.d.ts` but got this:

`Cannot find name 'Required'`

**Comment by aciccarello** [comment]
@alisahinozcelik did you get that error when running the current typedoc or the version in this PR?

**Comment by alisahinozcelik** [comment]
@aciccarello  I have got the error at tsdoc@0.11.1 and typescript@2.8.3

**Comment by pranavjindal999** [comment]
common guys, please upgrade the TS version.

Following fails :(

```ts
type DeepPartial<T> = {
  [key in keyof T]?: T[key] extends Object ? DeepPartial<T[key]> : T[key]
};
```

**Comment by arogozine** [comment]
FYI TypeScript 2.9 is out soon

**Comment by jasongrout** [comment]
See also #744.

**Comment by jasongrout** [comment]
Typescript 3.0 is out now.

Also, related issue: https://github.com/TypeStrong/typedoc/issues/822

**Comment by ahocevar** [comment]
#824 provides the updates to make TypeDoc work with TypeScript 3.1.x.

**Comment by athasach** [comment]
Addressed by https://github.com/TypeStrong/typedoc/pull/832
