### ISSUE TITLE
Typescript 4.5 broken in 0.22.16 & 0.23.0-beta.2

### ISSUE THREAD

**Issue by Julusian** [TypeStrong/typedoc#1945]
## Expected Behavior

Typedoc would work with typescript 4.5

## Actual Behavior

```
TypeDoc exiting with unexpected error:
TypeError: context.checker.getTypeOfSymbol is not a function
    at Object.convertProperty (/home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/symbols.js:370:176)
    at convertSymbol (/home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/symbols.js:132:88)
    at convertSymbols (/home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/symbols.js:138:9)
    at Object.convertClassOrInterface (/home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/symbols.js:301:5)
    at convertSymbol (/home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/symbols.js:132:88)
    at Converter.convertExports (/home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/converter.js:188:41)
    at /home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/converter.js:156:30
    at Array.forEach (<anonymous>)
    at Converter.compile (/home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/converter.js:154:17)
    at Converter.convert (/home/julus/Projects/typedoc-test/node_modules/typedoc/dist/lib/converter/converter.js:36:14)
```

## Steps to reproduce the bug

1. Clone https://github.com/Julusian/typedoc-test
1. `yarn install` (or `npm install`)
2. `npm run docs` or `yarn docs`

Removing the `_duration` property from the class `Test` causes the error to go away, so it is something to do with those private properties

Downgrading typedoc to 0.22.15 avoids this bug

## Environment

-   Typedoc version: 0.22.16 & 0.23.0-beta.2
-   TypeScript version: 4.5.5
-   Node.js version: v16.14.0 & v14.19.3
-   OS: Ubuntu 20.04/21.10

**Comment by Gerrit0** [comment]
I thought that function had been around... forever... easy fix at least...

**Comment by Gerrit0** [comment]
(Also: Not going to fix this for the beta version, 0.23 will drop support for TS < 4.6, following the [supported TS version policy](https://typedoc.org/guides/installation/#requirements), using this function allows getting rid of a hack I've wanted out of the code for over a year)

**Comment by Julusian** [comment]
Perfect, I can confirm that 0.22.17 is now working for me
Thanks for fixing this so quickly!
